name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test_lint:
    runs-on: ubuntu-latest
    if: ${{ !github.event.created && github.repository != 'garronej/ts-ci' }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
    - uses: bahmutov/npm-install@v1
    - name: If this step fails run 'npm run lint' and 'npm run format' then commit again.
      run: |
        PACKAGE_MANAGER=npm
        if [ -f "./yarn.lock" ]; then
            PACKAGE_MANAGER=yarn
        fi
        $PACKAGE_MANAGER run format:check
  test:
    runs-on: macos-10.15
    needs: test_lint
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    strategy:
      matrix:
        node: [ '15', '14' ]
    name: Test with Node v${{ matrix.node }}
    steps:
    - name: Tell if project is using npm or yarn
      id: step1
      uses: garronej/ts-ci@v1.1.4
      with: 
        action_name: tell_if_project_uses_npm_or_yarn
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: ${{ matrix.node }}
    - uses: bahmutov/npm-install@v1
    - if: steps.step1.outputs.npm_or_yarn == 'yarn'
      run: |
        yarn build
        yarn test
    - if: steps.step1.outputs.npm_or_yarn == 'npm'
      run: |
        npm run build
        npm test
  check_if_version_upgraded:
    name: Check if version upgrade
    # We run this only if it's a push on the default branch or if it's a PR from a 
    # branch (meaning not a PR from a fork). It would be more straightforward to test if secrets.NPM_TOKEN is 
    # defined but GitHub Action don't allow it yet.
    if: |
      github.event_name == 'push' || 
      github.event.pull_request.head.repo.owner.login == github.event.pull_request.base.repo.owner.login 
    runs-on: ubuntu-latest
    needs: test
    outputs:
      from_version: ${{ steps.step1.outputs.from_version }}
      to_version: ${{ steps.step1.outputs.to_version }}
      is_upgraded_version: ${{ steps.step1.outputs.is_upgraded_version }}
      is_release_beta: ${{steps.step1.outputs.is_release_beta }}
    steps:
    - uses: garronej/ts-ci@v1.1.4
      id: step1
      with: 
        action_name: is_package_json_version_upgraded
        branch: ${{ github.head_ref || github.ref }}

  create_github_release:
    runs-on: ubuntu-latest
    # We create a release only if the version have been upgraded and we are on a default branch
    # PR on the default branch can release beta but not real release
    if: |
      needs.check_if_version_upgraded.outputs.is_upgraded_version == 'true' &&
      (
        github.event_name == 'push' ||
        needs.check_if_version_upgraded.outputs.is_release_beta == 'true'
      )
    needs: 
      - check_if_version_upgraded
    steps:
    - uses: softprops/action-gh-release@v1
      with:
        name: Release v${{ needs.check_if_version_upgraded.outputs.to_version }}
        tag_name: v${{ needs.check_if_version_upgraded.outputs.to_version }}
        target_commitish: ${{ github.head_ref || github.ref }}
        generate_release_notes: true
        draft: false
        prerelease: ${{ needs.check_if_version_upgraded.outputs.is_release_beta == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

  publish_on_npm:
    runs-on: ubuntu-latest
    needs: 
      - create_github_release
      - check_if_version_upgraded
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: '15'
        registry-url: https://registry.npmjs.org/
    - uses: bahmutov/npm-install@v1
    - run: |
        PACKAGE_MANAGER=npm
        if [ -f "./yarn.lock" ]; then
            PACKAGE_MANAGER=yarn
        fi
        $PACKAGE_MANAGER run build
    - run: npx -y -p denoify@0.11.7 denoify_enable_short_npm_import_path
      env:
        DRY_RUN: "0"
    - name: Publishing on NPM
      run: |
        if [ "$(npm show . version)" = "$VERSION" ]; then
          echo "This version is already published"
          exit 0
        fi
        if [ "$NODE_AUTH_TOKEN" = "" ]; then
          echo "Can't publish on NPM, You must first create a secret called NPM_TOKEN that contains your NPM auth token. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets"
          false
        fi
        EXTRA_ARGS=""
        if [ "$IS_BETA" = "true" ]; then
            EXTRA_ARGS="--tag beta"
        fi
        npm publish $EXTRA_ARGS
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        VERSION: ${{ needs.check_if_version_upgraded.outputs.to_version }}
        IS_BETA: ${{ needs.check_if_version_upgraded.outputs.is_release_beta }}